# Usar uma imagem base do Node.js
FROM node:16-alpine

# Criar o diretório de trabalho dentro do contêiner
WORKDIR /app

# Copiar o package.json e o package-lock.json para o diretório de trabalho
COPY $PWD/package*.json ./


# Copiar os arquivos
COPY ./ ./

# Instalar as dependências
RUN yarn install

# Comando para executar o código gerador de usuários aleatórios
CMD ["node", "index.js"]